services:
  smart_home_auth_postgres:
    image: postgres:18.2-alpine
    container_name: smart_home_auth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    ports:
      - ${AUTH_POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_POSTGRES_USER}"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - microservices

  smart_home_store_postgres:
    image: postgres:18.2-alpine
    container_name: smart_home_store_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${STORE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${STORE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${STORE_POSTGRES_DB}
    volumes:
      - store_postgres_data:/var/lib/postgresql/data
    ports:
      - ${STORE_POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_POSTGRES_USER}"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - microservices

  smart_home_pgadmin:
    image: dpage/pgadmin4:9.12
    container_name: smart_home_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      smart_home_auth_postgres:
        condition: service_healthy
      smart_home_store_postgres:
        condition: service_healthy
    networks:
      - microservices

  smart_home_auth_service:
    build:
      context: AuthorizationService
      dockerfile: Dockerfile
    container_name: smart_home_auth_service
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - ${AUTH_SERVICE_PORT}:80
    depends_on:
      smart_home_auth_postgres:
        condition: service_healthy
    networks:
      - microservices

  smart_home_store_service:
    build:
      context: StoreService
      dockerfile: Dockerfile
    container_name: smart_home_store_service
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - ${STORE_SERVICE_PORT}:80
    depends_on:
      smart_home_store_postgres:
        condition: service_healthy
    networks:
      - microservices

  smart_home_gateway:
    build:
      context: _gateway
      dockerfile: Dockerfile
    container_name: smart_home_gateway
    restart: unless-stopped
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    depends_on:
      - smart_home_auth_service
      - smart_home_store_service
    networks:
      - microservices

networks:
  microservices:
    driver: bridge

volumes:
  auth_postgres_data:
  store_postgres_data:
  pgadmin_data:
